services:
  postgres:
    image: postgres:17
    container_name: library-postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"